# -*- coding: utf-8 -*-
itemset("",
	"DRAWING_HISTORY_FRAMES", True,
	"DRAWING_GLOBAL_PENCIL_VISIBLE", True,
	"DRAWING_GLOBAL_STICK_VISIBLE", False,
	"DRAWING_GLOBAL_STICK_ENABLED", False,
	"DRAWING_GLOBAL_STICK_SIZE", 1,
	"DRAWING_GLOBAL_STICK_TIP_SIZE", 1,
	"DRAWING_GLOBAL_STICK_TIP_FACTOR", 1,
	"DRAWING_GLOBAL_STICK_POS", (0, 0, 0),
	"DRAWING_GLOBAL_SEGMENT_SIZE", 1,
	"DRAWING_GLOBAL_SEGMENT_COLOR", (1, 1, 1, 1),
	"DRAWING_GLOBAL_STICK_POS_MAT", ((1, 1, 1), (0, 0, 0), (0, 0, 0)),
	"DRAWING_GLOBAL_PLAY_SPEED_END", 1,
	"DRAWING_GLOBAL_SHADOW_OFFSET", (0, 0, 0),
	"DRAWING_GLOBAL_SHADOW_COLOR", (0, 0, 0, 0),
	"DRAWING_GLOBAL_SMOOTH_AT_END", False,
	"DRAWING_GLOBAL_ARROW_AT_END", False,
	"DRAWING_GLOBAL_ARROW_AT_START", False,
	"DRAWING_GLOBAL_SHADOW_ENABLED", False,
	"DRAWING_GLOBAL_CLOSE_AT_END", False,
	"DRAWING_GLOBAL_LEAK_MODE", False,
	"DRAWING_PALETTE_COLORS", [\
		[1, 0, 0, 1], \
		[0, 1, 0, 1], \
		[0, 0, 1, 1], \
		[1, 1, 0, 1], \
		[1, 0, 1, 1], \
		[0, 1, 1, 1], \
		[0, 0, 0, 1], \
		[1, 1, 1, 1]],
	"DRAWING_PALETTE_SIZES", [\
1, \
2, \
3],
	"DRAWING_MACRO", [
	],
	"DRAWING_MACRO_TRACK", 1.1,
	"DRAWING_MACRO_LEADING", 1.3,
	"DRAWING_MACRO_SPACE", 0.5,
	"DRAWING_MACRO_GLOBAL_SCALE", 1,
	"DRAWING_MACRO_GLOBAL_THICKNESS", 1,
	"DRAWING_MACRO_GLOBAL_SPEED", 1)

