# -*- coding: utf-8 -*-
itemnew("folder", "Journalist",
	"FOLDER_LOCK_TAB", True,
	"FOLDER_DROP_AS_FIT", "Full",
	"FOLDER_DROP_AS_NEWLINE", True,
	"FOLDER_DROP_AS_LABEL_CHARS", 0,
	"FOLDER_DROP_AS_LABEL_WIDTH", 0,
	"FOLDER_DROP_AS_LABEL_JUSTIFY", "Left",
	"FOLDER_DROP_AS_EDITOR", True,
	"FOLDER_DROP_AS_CODE_EDITORS", ['<>VSET_CAMERAS/GoCamera'],
	"FOLDER_DROP_FORBIDDEN_EDITOR_TYPES", ['<>PIXMAP_DEG_GRAD', '<>OBJ_SETS'],
	"FOLDER_DROP_FORBIDDEN_EDITORS_BUT", ['<>MAP_HOLD'],
	"FOLDER_DROP_HEADER_EDITORS", False,
	"FOLDER_DROP_AS_DELETE_REF", True,
	"FOLDER_DROP_AS_LABEL_TYPE", "Name",
	"FOLDER_ICON", "Journalist",
	"FOLDER_VALUES_ROWS", 0)

